---
- name: "Watch for new Nautobot changelog entries"
  hosts: "localhost"
  sources:
    - networktocode.nautobot.nautobot_changelog:
        instance: "http://159.223.200.74:8080"
        token: "0123456789abcdef0123456789abcdef01234567"
        interval: 5
        query: ""

  rules:
    - name: "Find Interface based changelogs"
      condition: "event.meta is defined"
      actions:
        - debug:
            msg: "{{ event }}"
        - run_job_template:
            name: "Interface Change"
            organization: "Default"
              #job_args:
              #extra_vars:
              #interface_name: "{{ event.name }}"
              #  interface_state: "{{ event.enabled }}"

